# Generated by Django 3.0.2 on 2020-04-28 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='create_user',
        ),
    ]
