# Generated by Django 3.0.2 on 2020-05-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[(1, '字符串'), (2, '整形'), (3, '浮点型'), (4, '布尔'), (6, '时间'), (5, '日期'), (7, '日期时间'), (8, '范围日期'), (9, '文本域'), (10, '单选框'), (11, '下拉列表'), (12, '用户名')], default=0, max_length=1, verbose_name='字段类型'),
        ),
    ]
