# Generated by Django 3.0.3 on 2021-02-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowBpmn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('memo', models.TextField(blank=True, verbose_name='备注')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('status', models.BooleanField(default=True)),
                ('xml', models.TextField(blank=True, verbose_name='xml数据')),
                ('svg', models.TextField(blank=True, verbose_name='svg数据')),
                ('json', models.TextField(blank=True, verbose_name='json数据')),
            ],
            options={
                'verbose_name': '工作流bpmn',
                'verbose_name_plural': '工作流bpmn',
            },
        ),
    ]
