# Generated by Django 3.0.3 on 2021-02-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='workflow_set', related_query_name='workflow', to='systems.Role', verbose_name='关联角色'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='attribute_type',
            field=models.CharField(choices=[(0, '草稿'), (1, '待审'), (2, '驳回'), (3, '撤销'), (4, '结束'), (5, '已关闭')], default=0, max_length=1, verbose_name='属性类型'),
        ),
    ]
