# Generated by Django 3.0.2 on 2020-04-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_auto_20200424_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='type',
            new_name='state_type',
        ),
        migrations.RemoveField(
            model_name='transition',
            name='type',
        ),
        migrations.AddField(
            model_name='transition',
            name='transition_type',
            field=models.CharField(choices=[(0, '常规流转'), (1, '定时器流转')], default=0, max_length=1, verbose_name='流转类型'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='attribute_type',
            field=models.CharField(choices=[(0, '同意'), (1, '拒绝'), (2, '其他')], default=0, max_length=1, verbose_name='属性类型'),
        ),
    ]
