# Generated by Django 3.0.2 on 2020-05-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_auto_20200502_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[(1, '字符串'), (2, '整形'), (3, '浮点型'), (4, '布尔'), (5, '日期'), (6, '日期时间'), (7, '范围日期'), (8, '文本域'), (9, '单选框'), (10, '下拉列表'), (11, '用户名'), (12, '多选框'), (13, '多选下拉'), (14, '多选用户名')], default=0, max_length=1, verbose_name='字段类型'),
        ),
    ]
