# Generated by Django 3.0.3 on 2021-02-09 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_workflowbpmn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowbpmn',
            name='name',
        ),
        migrations.RemoveField(
            model_name='workflowbpmn',
            name='status',
        ),
        migrations.AddField(
            model_name='workflowbpmn',
            name='workflow',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflows.Workflow', verbose_name='工作流'),
            preserve_default=False,
        ),
    ]
