# Generated by Django 3.0.2 on 2020-04-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_remove_state_create_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtype',
            name='order_id',
            field=models.IntegerField(default=1, verbose_name='状态顺序'),
        ),
    ]
