# Generated by Django 3.0.2 on 2020-04-28 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_workflowtype_order_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowtype',
            options={'ordering': ['-order_id'], 'verbose_name': '类型', 'verbose_name_plural': '类型'},
        ),
    ]
