# Generated by Django 3.0.2 on 2020-04-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_auto_20200424_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
