# Generated by Django 3.0.3 on 2021-02-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_auto_20210209_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowbpmn',
            name='json',
        ),
        migrations.AddField(
            model_name='workflow',
            name='key',
            field=models.CharField(blank=True, max_length=168, verbose_name='流程标识key'),
        ),
    ]
