# Generated by Django 3.0.2 on 2020-04-29 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_auto_20200428_2347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowtype',
            options={'ordering': ['order_id'], 'verbose_name': '类型', 'verbose_name_plural': '类型'},
        ),
        migrations.RemoveField(
            model_name='state',
            name='state_field_str',
        ),
    ]
