# Generated by Django 3.0.2 on 2020-04-25 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_workflow_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='content_template',
        ),
    ]
