# Generated by Django 3.0.2 on 2020-04-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_remove_workflow_content_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfield',
            options={'ordering': ['order_id'], 'verbose_name': '工作流自定义字段', 'verbose_name_plural': '工作流自定义字段'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['order_id'], 'verbose_name': '工作流状态', 'verbose_name_plural': '工作流状态'},
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[(10, '字符串'), (15, '整形'), (20, '浮点型'), (25, '布尔'), (30, '日期'), (35, '时间'), (40, '日期时间'), (45, '单选框'), (50, '多选框'), (55, '下拉列表'), (60, '多选下拉列表'), (65, '文本域'), (70, '用户名'), (75, '多选的用户名')], default=0, max_length=1, verbose_name='字段类型'),
        ),
        migrations.AlterField(
            model_name='state',
            name='state_type',
            field=models.CharField(choices=[(0, '普通状态'), (1, '初始状态'), (2, '结束状态')], default=0, max_length=1, verbose_name='状态类型'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='transition_type',
            field=models.CharField(choices=[(0, '常规流转'), (2, '结束状态')], default=0, max_length=1, verbose_name='流转类型'),
        ),
    ]
