# Generated by Django 3.0.2 on 2020-04-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_auto_20200426_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='order_id',
            field=models.IntegerField(default=1, verbose_name='状态顺序'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='attribute_type',
            field=models.CharField(choices=[(0, '同意'), (1, '拒绝'), (2, '保存'), (3, '其他')], default=0, max_length=1, verbose_name='属性类型'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='transition_type',
            field=models.CharField(choices=[(0, '常规流转'), (1, '定时器流转')], default=0, max_length=1, verbose_name='流转类型'),
        ),
    ]
