# Generated by Django 3.0.2 on 2020-04-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_auto_20200429_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transition',
            name='name',
            field=models.CharField(choices=[(0, '保存'), (1, '转交下一步'), (2, '驳回'), (3, '撤销')], default=1, max_length=1, verbose_name='名称类型'),
        ),
    ]
