# Generated by Django 3.0.2 on 2020-04-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_auto_20200427_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='create_user',
            field=models.CharField(default='admin', max_length=50, verbose_name='创建者'),
            preserve_default=False,
        ),
    ]
