# Generated by Django 3.0.2 on 2020-04-30 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0009_auto_20200429_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_set', related_query_name='workflowtype', to='workflows.WorkflowType', verbose_name='工作流类型'),
        ),
    ]
