# Generated by Django 3.0.2 on 2020-04-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0009_auto_20200427_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='field_attribute',
            field=models.BooleanField(default=True, verbose_name='字段是否必填'),
        ),
    ]
