# Generated by Django 3.0.2 on 2020-04-30 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0010_auto_20200501_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.WorkflowType', verbose_name='工作流类型'),
        ),
    ]
