# Generated by Django 3.0.2 on 2020-05-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0012_auto_20200502_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='participant',
            field=models.CharField(blank=True, default='', help_text='可以为空(无处理人的情况，如结束状态)、username\\多个username(以,隔开)\\部门id\\角色id\\变量(creator,creator_tl)\\脚本记录的id等，包含子工作流的需要设置处理人为loonrobot', max_length=100, verbose_name='参与者'),
        ),
    ]
