# Generated by Django 3.0.2 on 2020-05-01 23:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('systems', '0002_auto_20200501_0625'),
        ('workflows', '0013_auto_20200502_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='participant',
        ),
        migrations.AddField(
            model_name='state',
            name='group_participant',
            field=models.ManyToManyField(blank=True, to='systems.Group', verbose_name='参与组'),
        ),
        migrations.AddField(
            model_name='state',
            name='role_participant',
            field=models.ManyToManyField(blank=True, to='systems.Role', verbose_name='参与角色'),
        ),
        migrations.AddField(
            model_name='state',
            name='user_participant',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='参与用户'),
        ),
    ]
