# Generated by Django 3.0.3 on 2020-09-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='relation',
            field=models.TextField(blank=True, default='', help_text='创建人、处理人，用于查询', verbose_name='工单关联人'),
        ),
    ]
