# Generated by Django 3.0.2 on 2020-04-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketcustomfield',
            name='field_type',
            field=models.CharField(choices=[(10, '字符串'), (15, '整形'), (20, '浮点型'), (25, '布尔'), (30, '日期'), (35, '时间'), (40, '日期时间'), (45, '单选框'), (50, '多选框'), (55, '下拉列表'), (60, '多选下拉列表'), (65, '文本域'), (70, '用户名'), (75, '多选的用户名')], default=0, max_length=1, verbose_name='字段类型'),
        ),
        migrations.AlterField(
            model_name='ticketcustomfield',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketflowlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
