# Generated by Django 3.0.2 on 2020-04-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20200426_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='create_user',
            field=models.CharField(default='admin', max_length=50, verbose_name='创建者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='act_state',
            field=models.CharField(choices=[(0, '草稿中'), (1, '进行中'), (2, '被退回'), (3, '被撤销'), (4, '已完成'), (5, '已关闭')], default=0, max_length=1, verbose_name='进行状态'),
        ),
    ]
