# Generated by Django 3.0.2 on 2020-04-29 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticketflowlog_ticket_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='customfield',
        ),
    ]
