# Generated by Django 3.0.2 on 2020-04-27 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20200427_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='sn',
            field=models.CharField(blank=True, help_text='工单的流水号', max_length=25, verbose_name='流水号'),
        ),
    ]
