# Generated by Django 3.0.2 on 2020-04-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_ticket_customfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='customfield',
            field=models.TextField(default=[], verbose_name='所有表单数据'),
        ),
    ]
