# Generated by Django 3.0.2 on 2020-04-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20200427_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='create_user',
            field=models.CharField(blank=True, max_length=50, verbose_name='创建者'),
        ),
    ]
