# Generated by Django 3.0.2 on 2020-04-27 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0009_auto_20200427_0921'),
        ('tickets', '0005_auto_20200427_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='act_state',
        ),
        migrations.AddField(
            model_name='ticket',
            name='transition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.Transition', verbose_name='进行状态'),
        ),
    ]
