# Generated by Django 3.0.2 on 2020-04-27 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20200427_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='participant_type',
        ),
    ]
