# Generated by Django 3.0.2 on 2020-04-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='participant',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='当前处理人'),
        ),
    ]
