# Generated by Django 3.0.2 on 2020-04-30 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20200430_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketflowlog',
            name='participant_type',
        ),
    ]
