# Generated by Django 3.0.2 on 2020-04-27 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0009_auto_20200427_0921'),
        ('tickets', '0007_auto_20200427_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcustomfield',
            options={'verbose_name': '工单自定义字段值', 'verbose_name_plural': '工单自定义字段值'},
        ),
        migrations.RemoveField(
            model_name='ticketcustomfield',
            name='bool_value',
        ),
        migrations.RemoveField(
            model_name='ticketcustomfield',
            name='char_value',
        ),
        migrations.RemoveField(
            model_name='ticketcustomfield',
            name='checkbox_value',
        ),
        migrations.RemoveField(
            model_name='ticketcustomfield',
            name='date_value',
        ),
        migrations.RemoveField(
            model_name='ticketcustomfield',
            name='datetime_value',
        ),
        migrations.RemoveField(
            model_name='ticketcustomfield',
            name='field_key',
        ),
        migrations.RemoveField(
            model_name='ticketcustomfield',
            name='field_type',
        ),
        migrations.RemoveField(
            model_name='ticketcustomfield',
            name='float_value',
        ),
        migrations.RemoveField(
            model_name='ticketcustomfield',
            name='int_value',
        ),
        migrations.RemoveField(
            model_name='ticketcustomfield',
            name='multi_select_value',
        ),
        migrations.RemoveField(
            model_name='ticketcustomfield',
            name='multi_username_value',
        ),
        migrations.RemoveField(
            model_name='ticketcustomfield',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ticketcustomfield',
            name='radio_value',
        ),
        migrations.RemoveField(
            model_name='ticketcustomfield',
            name='select_value',
        ),
        migrations.RemoveField(
            model_name='ticketcustomfield',
            name='text_value',
        ),
        migrations.RemoveField(
            model_name='ticketcustomfield',
            name='time_value',
        ),
        migrations.RemoveField(
            model_name='ticketcustomfield',
            name='username_value',
        ),
        migrations.AddField(
            model_name='ticketcustomfield',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflows.CustomField', verbose_name='字段'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketcustomfield',
            name='field_value',
            field=models.TextField(blank=True, default='', verbose_name='字段值'),
        ),
    ]
