# Generated by Django 3.0.2 on 2020-04-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_remove_ticketflowlog_participant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketuser',
            name='username',
            field=models.CharField(default=1, max_length=100, verbose_name='关系人'),
            preserve_default=False,
        ),
    ]
