# Generated by Django 3.0.2 on 2020-04-30 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0009_auto_20200430_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(blank=True, default='', max_length=112, verbose_name='标题'),
        ),
    ]
