# Generated by Django 3.0.2 on 2020-04-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20200427_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='customfield',
            field=models.TextField(default=[], verbose_name='所有表单数据'),
        ),
    ]
