# Generated by Django 3.0.2 on 2020-04-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_auto_20200427_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='multi_all_person',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='sn',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='workflow',
            field=models.CharField(blank=True, help_text='工单的流水号', max_length=25, verbose_name='流水号'),
        ),
    ]
