# Generated by Django 3.0.2 on 2020-04-27 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0010_customfield_field_attribute'),
        ('tickets', '0012_auto_20200427_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sn',
            field=models.CharField(blank=True, help_text='工单的流水号', max_length=25, verbose_name='流水号'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.Workflow', verbose_name='工作流'),
        ),
    ]
