# Generated by Django 3.0.2 on 2020-04-27 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_auto_20200427_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='relation',
        ),
    ]
