# Generated by Django 3.0.2 on 2020-04-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbot',
            name='type',
            field=models.CharField(choices=[('mail', 'mail'), ('telegram', 'telegram')], default=0, max_length=10, verbose_name='通知类型'),
        ),
        migrations.AlterField(
            model_name='telegrambot',
            name='type',
            field=models.CharField(choices=[('mail', 'mail'), ('telegram', 'telegram')], default=0, max_length=10, verbose_name='通知类型'),
        ),
    ]
