# Generated by Django 3.0.2 on 2020-04-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='active_menu',
            field=models.CharField(default=1, max_length=32, verbose_name='激活菜单'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='no_cache',
            field=models.BooleanField(default=True, verbose_name='菜单是否缓存'),
        ),
    ]
