# Generated by Django 3.0.2 on 2020-04-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_auto_20200425_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='active_menu',
            field=models.CharField(default='/', max_length=32, verbose_name='激活菜单'),
        ),
    ]
