# Generated by Django 3.0.2 on 2020-04-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_auto_20200426_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='active_menu',
            field=models.CharField(blank=True, max_length=32, verbose_name='激活菜单'),
        ),
    ]
